### Create Customer
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "email": "max@example.com"
}

### Get Customers
GET http://localhost:8080/api/customers

### Create Account for Customer 1
POST http://localhost:8080/api/accounts/customer/1

### Get Accounts
GET http://localhost:8080/api/accounts

### Deposit 500
POST http://localhost:8080/api/accounts/1/deposit?amount=500

### Get Accounts
GET http://localhost:8080/api/accounts

### Withdraw 200
POST http://localhost:8080/api/accounts/1/withdraw?amount=200

### Get Accounts
GET http://localhost:8080/api/accounts