### Create Customer 1
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "firstName": "Fabian",
  "lastName": "Kasten",
  "email": "fabian@kasten.com"
}

### Create Customer 2
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "email": "max@mustermann.com"
}

### Get Customers
GET http://localhost:8080/api/customers

### Create Account for Customer 1
POST http://localhost:8080/api/accounts/customer/1

### Create Account for Customer 2
POST http://localhost:8080/api/accounts/customer/2

### Get Accounts
GET http://localhost:8080/api/accounts

### Deposit 500
POST http://localhost:8080/api/accounts/1/deposit?amount=500

### Withdraw 200
POST http://localhost:8080/api/accounts/1/withdraw?amount=200

### Transfer 100 from Account 1 to Account 2
POST http://localhost:8080/api/accounts/1/transfer/2?amount=100

### Get Transactions Account 1
GET http://localhost:8080/api/transactions/account/1

### Get Transactions Account 2
GET http://localhost:8080/api/transactions/account/2

### Throw Account not found Exception for deposit
POST http://localhost:8080/api/accounts/999/deposit?amount=100

### Throw Account not found Exception for transaction
GET http://localhost:8080/api/transactions/account/999